import { questerSpec } from "@/lib/quester";

// The mark is not drawn, it is derived. Feeding "ckb-quest" through the same
// hash the product uses for every player's Quester returns this shape and this
// colour. The logo is a Quester, generated by the rules it is a logo for.
export const MARK_SEED = "ckb-quest";

export default function Mark({
  size = 22,
  gap = true,
}: {
  size?: number;
  gap?: boolean;
}) {
  const { grid, color, cells } = questerSpec(MARK_SEED);
  const unit = size / grid;
  const inset = gap ? unit * 0.08 : 0;

  return (
    <svg
      width={size}
      height={size}
      viewBox={`0 0 ${grid} ${grid}`}
      shapeRendering="crispEdges"
      aria-hidden="true"
      style={{ display: "block", flexShrink: 0 }}
    >
      {cells.map((row, y) =>
        row.map((on, x) =>
          on ? (
            <rect
              key={`${x}-${y}`}
              x={x + inset}
              y={y + inset}
              width={1 - inset * 2}
              height={1 - inset * 2}
              fill={color}
            />
          ) : null,
        ),
      )}
    </svg>
  );
}
