// The mark is not drawn, it is derived. Feeding "ckb-quest" through the same
// hash the product uses for every player's Quester returns this shape and this
// colour. The logo is a Quester, generated by the rules it is a logo for.
//
// It lives in lib rather than beside the component because the icon and the OG
// image are generated at the app root, outside the marketing route group, and
// reaching across a route group for a constant is not worth the import path.
export const MARK_SEED = "ckb-quest";
